feat: :sparkles: add configurable DNS addresses #30
bepass-org/warp-plus pull request #103
Opened 2024-05-18 14:05 UTC by pizokh

- Added default DNS addresses and a command-line option (--dns-addr) to customize them.

2024-05-18 22:37 UTC, markpash reviewed
Good Job! I've left some comments for some changes.

2024-05-18 22:37 UTC, markpash commented on app/app.go
> +	DnsAddr  []string
Change this from `[]string` to `netip.Addr`.

2024-05-18 22:37 UTC, markpash commented on main.go
> +		dnsAddr  = fs.StringList('d', "dns-addr", fmt.Sprintf("DNS addresses (default: %v)", defaultDnsAddr))
Let's change this to be a single string, using `fs.StringLong` and that should allow you to specify the default directly here. Let's just make the default `1.1.1.1`.

2024-05-18 22:37 UTC, markpash commented on main.go
> +var defaultDnsAddr = []string{
Let's just get rid of this list, it causes more confusion for users. We'll just use `1.1.1.1` as the default.

2024-05-18 22:37 UTC, markpash commented on main.go
> +	if len(*dnsAddr) == 0 {
This won't be needed if the above comments are implemented.

2024-05-18 22:37 UTC, markpash commented on warp/account.go
> +	for index, server := range dnsAddr {
Instead of writing out the DNS here, what we should do is remove it from here, and do it in each of the `runWarp(), runWarpInWarp() and runWarpWithPsiphon()` functions in `app.go`. Just like how `conf.Interface.MTU` is set, we should have a `conf.Interface.DNS`.

2024-05-19 09:39 UTC, pizokh commented
Thank you for the feedback, @markpash! I have made the requested changes:

- Changed `DnsAddr` from `[]string` to `netip.Addr` in `WarpOptions`.
- Updated the command-line option to be a single string using `fs.StringLong` with `1.1.1.1` as the default.
- Removed the `defaultDnsAddr` list and associated logic.
- Adjusted the DNS setup to be handled directly in `runWarp()`, `runWarpInWarp()`, and `runWarpWithPsiphon()` functions.
- Updated the `createConf` and `LoadOrCreateIdentity` functions to reflect these changes.

Please review the updated implementation. Let me know if any further adjustments are needed.

2024-05-19 10:44 UTC, markpash requested changes

2024-05-19 10:44 UTC, markpash commented on wiresocks/config.go
> +			addresses = append(addresses, ip)
You probably shouldn't use `append()` when you know the size of the resulting slice beforehand.
Consider the following:
```go
addrs := sectionKey.StringsWithShadows(",")
device.DNS = make([]netip.Addr, len(addrs))
for i, addr := range addrs {
    ip, err := netip.ParseAddr(str)
    if err != nil {
        return InterfaceConfig{}, err
    }
    device.DNS[i] = ip
}
```

2024-05-19 10:44 UTC, markpash commented on main.go
> +		dns      = fs.StringLong("dns-addr", "1.1.1.1", "DNS address")
Let's just make this `dns` instead of `dns-addr`.
Also please don't forget to add the line to the example config json file.

2024-05-19 10:45 UTC, markpash commented on main.go
> +		dns      = fs.StringLong("dns-addr", "1.1.1.1", "DNS address")
Also don't forget to edit your commit message as well.

2024-05-19 12:23 UTC, markpash approved these changes

2024-05-19 12:23 UTC, merged

2024-05-24 10:38 UTC, sarobakhtiyari approved these changes

2024-05-24 10:39 UTC, sarobakhtiyari approved these changes